sudo: required
language: python
python:
- '2.7'
services:
- docker
before_install:
- docker build -t mcallb/twitter-stream .
script: echo 'Hello Build'
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push mcallb/twitter-stream; fi
deploy:
  provider: lambda
  function_name: write_distinct_handle
  region: us-east-1
  role: arn:aws:iam::354280536914:role/service-role/LambdaRole
  runtime: python2.7
  zip: lambda/write_distinct_handle.py
  handler_name: write_distinct_handle.lambda_handler
  access_key_id: AKIAJM3N2QMHQMRCAV2A
  secret_access_key:
    secure: RQr0uCCADWqSctrBKfmA2d/uRg6s4uberTmADhXV11kO45suMASf/gCwS46Mq1Htvof49umMPZbaco7NcP4pvocTkfJV8C7LAeN996gCGRYP87uTGLdo5UxEqu/efz2e0/v8uwUF4gAhs5srySAUyke5mHqt/LNsXyVDWguhbWPaV2vpGfPL0/EGA+G3ZweXpd3Zz5auu7zD+kwxl60GjlG897SuXHaz6nWx+YhieQ4MK5QnTeDhnODuoJ2r9gPX3wZlRcB2ftzNR58GJbRW07L9GkIY+napUfUkQKGdAg8Bw5GebNQtTwNzWZfTuHNpIbTfNbpEGvY0hCNDf+llAONSgqylC/Z1AE7jXahsIsy3+Jky9gaHKOIVt3BMMYhUlD44+IZPxqud75U6YkXrApkhWAa4wze8AxUp2ZwiOn1+GC1FrkQkdWvCBhNIN2L1Q7pm5L09rOgAGG/UjoQkPVrKI1dVJH7V5Qmc6zy+XL8C4MRyrqA1kUEGDYi4FG+tDAud3arZ4pOTjOWiHMvSML6UpZBLIEjcZY19hYl2irPpOUtNuvMqxooVqU94SFc1S+WjDK+WMYcz3GtMVJ1wOVMaVbidNuMXTEWApU5//EpbQx9Lav5jCFfY4G9NiIbuhhjaMV44wGLfXgZ/cixxBTceKRQkoixOqZ4ujovaxdw=
deploy:
  provider: lambda
  function_name: write_distinct_search
  region: us-east-1
  role: arn:aws:iam::354280536914:role/service-role/LambdaRole
  runtime: python2.7
  zip: lambda/write_distinct_search.py
  handler_name: write_distinct_search.lambda_handler
  access_key_id: AKIAJM3N2QMHQMRCAV2A
  secret_access_key:
    secure: RQr0uCCADWqSctrBKfmA2d/uRg6s4uberTmADhXV11kO45suMASf/gCwS46Mq1Htvof49umMPZbaco7NcP4pvocTkfJV8C7LAeN996gCGRYP87uTGLdo5UxEqu/efz2e0/v8uwUF4gAhs5srySAUyke5mHqt/LNsXyVDWguhbWPaV2vpGfPL0/EGA+G3ZweXpd3Zz5auu7zD+kwxl60GjlG897SuXHaz6nWx+YhieQ4MK5QnTeDhnODuoJ2r9gPX3wZlRcB2ftzNR58GJbRW07L9GkIY+napUfUkQKGdAg8Bw5GebNQtTwNzWZfTuHNpIbTfNbpEGvY0hCNDf+llAONSgqylC/Z1AE7jXahsIsy3+Jky9gaHKOIVt3BMMYhUlD44+IZPxqud75U6YkXrApkhWAa4wze8AxUp2ZwiOn1+GC1FrkQkdWvCBhNIN2L1Q7pm5L09rOgAGG/UjoQkPVrKI1dVJH7V5Qmc6zy+XL8C4MRyrqA1kUEGDYi4FG+tDAud3arZ4pOTjOWiHMvSML6UpZBLIEjcZY19hYl2irPpOUtNuvMqxooVqU94SFc1S+WjDK+WMYcz3GtMVJ1wOVMaVbidNuMXTEWApU5//EpbQx9Lav5jCFfY4G9NiIbuhhjaMV44wGLfXgZ/cixxBTceKRQkoixOqZ4ujovaxdw=
