sudo: required
language: python
python:
- '2.7'
services:
- docker
before_install:
- docker build -t mcallb/twitter-stream .
script: echo 'Hello Build'
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push mcallb/twitter-stream; fi
deploy:
  provider: lambda
  function_name: write_distinct_handle
  region: us-east-1
  role: arn:aws:iam::354280536914:role/service-role/LambdaRole
  runtime: python2.7
  handler_name: lambda_handler
  access_key_id: AKIAJM3N2QMHQMRCAV2A
  secret_access_key:
    secure: CqHZGhHYgvODebSpd3nz5oXHnnOJZfvhowu5Ca+O7KgbWj+A9Rqw6TjARYCdVcnrlMRP/lwVzmuli71nYKoH4//L6rnn/oExpsdp2cLszBVyVJKZO8cU5Wk2BVNrxvZzuEEaupDVHu0JoFDsP8Ae3O+bY2L0VA8E8oX5388PT3Djj0TCMxPYLD+2pQGcMwk2jUo5abDyxJaMN1uk+fAfsu01OHtqquT8Sn9Fb0GjdvGj9ZtrUUTegD1UPB02Hw97bwQefaXP3jI/LH1mPXN6aFQnOLMVhKokFcNVhxbH2rNNyv7w1d4K1Xu5kPnCSIe5zAXcVE8jvGqSTG15HDOknlrcJ+rjx4C9+43wcfFOLVpLbTcdoL7ano7K0R/3MIe4yyfdDqAcKGsLLH1FChIKCMlqt8XZU1pPoymELgAGVo7UIMJJzbmx5/wYHAkxm9BBlmOWqbdIarNtlICmjIs6eDsQNX8xfzniLPY6KrrkhmSgHf61AhkgvlbrOxTn3vKyxqagridoofEHEoibiSjfFH46tSKC/7K7gZGOagTO2p2ja2EsJRk3NsCpvgbBJGo6AGuAYIENL1gLydUwnQqTxqaSG8eLQNAxZGEJsOnHugfnMZpYLIcTfe+owmpr7sW0hOnhRA/nTpcnjdsKpscmvyWvsOBZW19WIKGDNttHG34=
